version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: carbon-footprint-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carbon_footprint
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carbon-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: carbon-footprint-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - carbon-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbon-footprint-api
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/carbon_footprint
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=True
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - carbon-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  carbon-network:
    driver: bridge

volumes:
  postgres_data: 